### ISSUE TITLE
No app config

### ISSUE THREAD

**Issue by dbajal** [sontek/pyramid_celery#49]
Hi there. As documented, I do next:
ini:
```
[celery]
BROKER_URL = redis://0.0.0.0:6379/0
CELERY_IMPORTS = my.module.tasks

[app:main]
egg = another.module
pyramid.includes =
    ...
    pyramid_celery
...
```

another.module:
```python
<...>
def main(global_config, **settings):
    <...>
    config.configure_celery(global_config['__file__'])
```

my.module.tasks
```python
from pyramid_celery import celery_app as app

print app.conf['PYRAMID_REGISTRY']

@app.task()
def my_task():
    <...>
```

Then I run worker or I run application with pserve by .ini file, and application fails with
KeyError: 'PYRAMID_REGISTRY'.

Question is: what am I doing wrong? How do I access pyramid config in my tasks?

**Comment by sontek** [comment]
@dbajal The app.conf wont be registered at import time, it will be registered after your application is started in the `main` of your pyramid app or within the task itself.   If you move your print to application init time or within the task it'll work.
