### ISSUE TITLE
Cron job timing

### ISSUE THREAD

**Issue by crooksey** [sontek/pyramid_celery#53]
I have some cron tasks, then ones the are every 2 hours etc work fine, the ones where I specify an exact time to run, or day of the week, simply never execute, anything I am doing wrong?

    # Check every 2 hours for orders with nil_value
	# THIS WORKS FINE
	[celerybeat:task3]
	task = intranet.celery_tasks.nilvalue_celery
	type = crontab
	schedule = {"minute": 0, "hour": "*/2"}
        
    #THESE DO NOT WORK
	[celerybeat:task4]
	task = intranet.celery_tasks.emailfigures_celery
	type = crontab
	schedule = {"hour": "16", "minute": "30" }
	#schedule = {}

	[celerybeat:task5]
	task = intranet.celery_tasks.reps_pastweek_celery
	type = crontab
	schedule = {"day_of_week": 5, "hour": "16", "minute": "30"}
	# schedule = {"day_of_week":"Friday", "hour": "16", "minute": "30"}
	# schedule = {"day_of_week":"Fri", "hour": "16", "minute": "30"}

**Comment by sontek** [comment]
By default celery times are going to be `UTC` not your local time, so 16:30 would be 4:30 UTC.  If you want to have it in your local time you need to set `CELERY_TIMEZONE` underneath the [celery] configuration option.

I'm updating `pyramid_celery` docs to discuss this but you can see the celery information for that here:
http://celery.readthedocs.org/en/latest/userguide/periodic-tasks.html#time-zones

**Comment by sontek** [comment]
I added docs here:
https://github.com/sontek/pyramid_celery#worker-execution

and timezone docs here:
https://github.com/sontek/pyramid_celery/commit/a8633878ad19f9a2b6955ec87fb652adda846ad0
