### ISSUE TITLE
Admins list isn't read correctly

### ISSUE THREAD

**Issue by edelooff** [sontek/pyramid_celery#55]
I've been working on hooking up Celery with Pyramid and ran into what I think is a limitation of the ini-based configuration.

To get error-mails sent when a task fails, I need to set the `ADMINS` list. However, adding an admins variable in the [celery] config section makes this a string rather than the list of 2-tuples that Celery wants. Adding it to the `list_settings` list also doesn't work, as that makes a flat list, which is not accepted.

Extending the `read_configuration()` method of the `INILoader` class with the following (after processing list_settings) does the trick, though I'm not sure it's the best possible solution.

``` python
# Following after list_settings parsing

tuple_list_settings = ['ADMINS']

for setting in tuple_list_settings:
    if setting in config_dict:
        items = config_dict[setting].split()
        tuple_settings = [tuple(item.split(',')) for item in items]
        config_dict[setting] = tuple_settings
```

The corresponding ini file would look like this:

``` ini
[celery]
admins =
    development,development@example.com
    excecptions,exceptions@example.com
```

**Comment by sontek** [comment]
Fixed in 3.0.0!
