### ISSUE TITLE
options for celerybeat?

### ISSUE THREAD

**Issue by jgmtzmd** [sontek/pyramid_celery#64]
hi.
i was able to launch periodic tasks using something like this:

    [celery]
    BROKER_URL = redis://localhost:6379/0
    CELERY_RESULT_BACKEND = redis://
    CELERY_INCLUDE = miniscada.taskos
    CELERY_REDIRECT_STDOUTS_LEVEL = info
    CELERYD_CONCURRENCY = 3

    [celerybeat:task1]
    task = miniscada.taskos.lee_medidor
    type = timedelta
    schedule = {"seconds": 15}

it works fine. i tried to use options appending a line:
    [celerybeat:task1]
    task = miniscada.taskos.lee_medidor
    type = timedelta
    schedule = {"seconds": 15}
    options = {"task_id" : "4445",}

but it doesnt work. is there a way we can pass options to the beat task ?

**Comment by sontek** [comment]
Fixed in pyramid_celery v4
