### ISSUE TITLE
pyramid_celery fails silently when the inifile is not well configured

### ISSUE THREAD

**Issue by tonthon** [sontek/pyramid_celery#66]
In the pyramid_celery/__init__.py file, inside on_preload_parsed function the pyramid app is bootstraped using 
```python
env = bootstrap(ini_location, options=options)
```
or
```python
env = bootstrap(ini_location)
```
When that call fails, the celery_app starts without having been customized with default configuration.

For example running the long_running_task_with_tm example results by default in the following error. 
```console
[2017-09-28 17:36:35,569: WARNING/MainProcess] consumer: Cannot connect to %s: %s.
%s
[2017-09-28 17:36:35,569: WARNING/MainProcess] amqp://guest:**@127.0.0.1:5672//
[2017-09-28 17:36:35,569: WARNING/MainProcess] [Errno 111] Connection refused
[2017-09-28 17:36:35,570: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds...
```

Adding a traceback print shows : 
```console
InterpolationMissingOptionError: Error in file /home/mysuser/pool/pyramid_celery/examples/long_running_with_tm/development.ini: Bad value substitution:
	section: [app:main]
	option : sqlalchemy.url
	key    : database
	rawval : postgresql://localhost/%(database)s
```

**Comment by fmigneault** [comment]
I just saw the same behavior because of requirements failure.
The bootstrap raised the mismatch but didn't fail completely, so celery execution resumed with basically whatever else was left on the command line (not much), so most parameters used defaults.

**Comment by joesteeve** [comment]
`pyramid_celery` should log something when `bootstrap()` throws.
