### ISSUE TITLE
broker_transport_options seems to not work with celery 4.1

### ISSUE THREAD

**Issue by fjvt** [sontek/pyramid_celery#67]
when i set BROKER_TRANSPORT_OPTIONS = {"confirm_publish": True} in my ini file celery fails to load

(pyramid_celery gives the dict as a string to celery and it seems to choke on that)

added this to pyramid_celery/loaders.py

 dict_settings = ['BROKER_TRANSPORT_OPTIONS']

        import ast
        for setting in dict_settings:
           if setting in config_dict:
               config_dict[setting] = ast.literal_eval(config_dict[setting])

Seems to fix the issue (celery starts perfectly) ... no idea if this is the proper way but it works.

**Comment by sontek** [comment]
Fixed in pyramid_celery v4
