### ISSUE TITLE
pyramid_celery is not compatible with pyramid 2

### ISSUE THREAD

**Issue by tonthon** [sontek/pyramid_celery#79]
In pyramid 2 there is no pyramid.compat module anymore.
The ConfigParser should be loaded directly from the python3 configparser module.

```
from pyramid.compat import configparser
```
Should be
```
import configparser
```

**Comment by sontek** [comment]
I've fixed this is master, release should be out in the next few days.  Trying to get celery v5 to work first

**Comment by tonthon** [comment]
I was just looking if there was any update today and saw (with pleasure) that you were working on it again.
Thanks a lot.

**Comment by sontek** [comment]
Fixed in pyramid_celery v4
